### ISSUE TITLE
Error when trying to run recognize

### ISSUE THREAD

**Issue by ngzhongcai** [googleapis/nodejs-speech#142]
TypeError: require(...).demand(...).command(...).command(...).command(...).command(...).command(...).command(...).command(...).command(...).options(...).example(...).example(...).example(...).example(...).wrap(...).recommendCommands is not a function
    at Object.<anonymous> (/Users/ngfamily/Desktop/VOICE/recognize.js:581:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by ku294714** [comment]
Hi Sir, 

Can you please let me know the solution of this root cause?. Even I am facing the similar error.

**Comment by JustinBeckwith** [comment]
Greetings folks!  If you're running into problems, please create a new issue with:
- The code you're trying to run 
- What version of nodejs you're using
- What error you're getting

Thanks!
