### ISSUE TITLE
Fix failing samples test

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-speech#167]
Samples tests have been failing for a while now - let's fix them!

```
  ✔ MicrophoneStream › MicrophoneStream.js Should load and display Yaaaarghs(!) correctly (189ms)
  ✔ betaFeatures › should run word Level Confience on a local file (2s)
  ✖ betaFeatures › should run word level confidence on a GCS bucket 
  ✔ betaFeatures › should transcribe multi-language on a local file (3.4s)
  ✔ betaFeatures › should transcribe multi-language on a GCS bucket (3.8s)
  ✔ betaFeatures › should run multi channel transcription on GCS file (6.6s)
  ✔ betaFeatures › should run speech diarization on a GCS file (7.9s)
  ✔ betaFeatures › should run multi channel transcription on a local file (8.5s)
  ✔ betaFeatures › should run speech diarization on a local file (9.2s)
  ✔ recognize.v1p1beta1 › should run sync recognize with enhanced model (9s)
  ✔ recognize.v1p1beta1 › should run sync recognize with metadata (9.4s)
  ✔ recognize.v1p1beta1 › should run sync recognize with auto punctuation (9.5s)
  ✖ recognize › should run streaming recognize Rejected promise returned by test
  ✔ recognize › should run sync recognize (1.9s)
  ✔ recognize › should run sync recognize with word time offset (1.9s)
  ✔ recognize › should run sync recognize on a GCS file (2s)
  ✔ recognize › should run async recognize on a GCS file with word time offset (2.3s)
  ✔ recognize › should run async recognize on a local file (2.5s)
  ✔ recognize › should run async recognize on a GCS file (2.5s)
  ✔ quickstart › should run quickstart (1.7s)
  ✔ recognize.v1p1beta1 › should run sync recognize with model selection (16s)
  ✔ recognize.v1p1beta1 › should run sync recognize on a GCS file with model selection (16.6s)

  2 tests failed

  betaFeatures › should run word level confidence on a GCS bucket

  /home/node/samples/samples/system-test/betaFeatures.test.js:106

   105:   );                                                                   
   106:   t.true(                                                              
   107:     output.includes(`Transcription: how old is the Brooklyn Bridge`) &&

  Value is not `true`:

  false

  output.includes(`Transcription: how old is the Brooklyn Bridge`) && output.includes(`Confidence: \d\.\d`)
  => false

  output.includes(`Confidence: \d\.\d`)
  => false

  `Confidence: \d\.\d`
  => 'Confidence: d.d'

  output
  => `Transcription: how old is the Brooklyn Bridge ␊
   Confidence: 0.9836039543151855␊
  Word-Level-Confidence:␊
   word: how, confidence: 0.9876290559768677␊
   word: old, confidence: 0.9692915678024292␊
   word: is, confidence: 0.982710063457489␊
   word: the, confidence: 0.982710063457489␊
   word: Brooklyn, confidence: 0.9876290559768677␊
   word: Bridge, confidence: 0.9876290559768677`

  output.includes(`Transcription: how old is the Brooklyn Bridge`)
  => true

  `Transcription: how old is the Brooklyn Bridge`
  => 'Transcription: how old is the Brooklyn Bridge'

  output
  => `Transcription: how old is the Brooklyn Bridge ␊
   Confidence: 0.9836039543151855␊
  Word-Level-Confidence:␊
   word: how, confidence: 0.9876290559768677␊
   word: old, confidence: 0.9692915678024292␊
   word: is, confidence: 0.982710063457489␊
   word: the, confidence: 0.982710063457489␊
   word: Brooklyn, confidence: 0.9876290559768677␊
   word: Bridge, confidence: 0.9876290559768677`



  recognize › should run streaming recognize

  /home/node/samples/samples/recognize.js:392

   391:       console.log(                                                    
   392:         `Transcription: ${data.results[0].alternatives[0].transcript}`
   393:       );                                                              

  Rejected promise returned by test. Reason:

  Error {
    cmd: 'node recognize.js stream /home/node/samples/samples/resources/audio.raw',
    code: 1,
    killed: false,
    signal: null,
    message: `Command failed: node recognize.js stream /home/node/samples/samples/resources/audio.raw␊
    (node:431) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead␊
    /home/node/samples/samples/recognize.js:392␊
            `Transcription: ${data.results[0].alternatives[0].transcript}`␊
                                              ^␊
    ␊
    TypeError: Cannot read property 'alternatives' of undefined␊
        at Pumpify.client.streamingRecognize.on.on.data (/home/node/samples/samples/recognize.js:392:43)␊
        at emitOne (events.js:116:13)␊
        at Pumpify.emit (events.js:211:7)␊
        at addChunk (/home/node/samples/node_modules/readable-stream/lib/_stream_readable.js:291:12)␊
        at readableAddChunk (/home/node/samples/node_modules/readable-stream/lib/_stream_readable.js:278:11)␊
        at Pumpify.Readable.push (/home/node/samples/node_modules/readable-stream/lib/_stream_readable.js:245:10)␊
        at Pumpify.Duplexify._forward (/home/node/samples/node_modules/duplexify/index.js:170:26)␊
        at DestroyableTransform.onreadable (/home/node/samples/node_modules/duplexify/index.js:134:10)␊
        at emitNone (events.js:106:13)␊
        at DestroyableTransform.emit (events.js:208:7)␊
    `,
  }

  Pumpify.client.streamingRecognize.on.on.data (recognize.js:392:43)
  addChunk (/home/node/samples/node_modules/readable-stream/lib/_stream_readable.js:291:12)
  readableAddChunk (/home/node/samples/node_modules/readable-stream/lib/_stream_readable.js:278:11)
  Pumpify.Readable.push (/home/node/samples/node_modules/readable-stream/lib/_stream_readable.js:245:10)
  Pumpify.Duplexify._forward (/home/node/samples/node_modules/duplexify/index.js:170:26)
  DestroyableTransform.onreadable (/home/node/samples/node_modules/duplexify/index.js:134:10)
```

**Comment by JustinBeckwith** [comment]
These appear to be fixed 🎉
