### ISSUE TITLE
node: uncaughtException error on RESOURCE_EXHAUSTED: Quota exceeded

### ISSUE THREAD

**Issue by kidplug** [googleapis/nodejs-speech#425]
In my application, when reaching the quota:
speech.googleapis.com/default_requests
DefaultRequestsPerMinutePerProject
(which is 300 by default) - 

The immediate caller to the library receives an error (via `errHandler` below) - but the main node process also gets an `uncaughtException`  via `process.on("uncaughtException",function(err){ ... `

eg:
```
var gspeech = require("@google-cloud/speech");
var client = new gspeech.SpeechClient( someAuth );
var stream = parent.client.streamingRecognize( someConfig );
stream.on("data", dataHandler);
stream.on("error", errHandler);
```

Obviously this is highly undesirable, as the entire application/process exits at that point.

The library should throw this error to the caller via the `errHandler`  but it should *NOT* crash the entire node process due to a resource/quota being reached.

**Comment by kidplug** [comment]
full error:

```
{ Error: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'speech.googleapis.com/default_requests' and limit 'DefaultRequestsPerMinutePerProject' of service 'speech.googleapis.com' for consumer 'project_number:###########'.
    at Object.exports.createStatusError (/home2/arcos/arcos-app/arcos10-fsivr/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home2/arcos/arcos-app/arcos10-fsivr/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/home2/arcos/arcos-app/arcos10-fsivr/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home2/arcos/arcos-app/arcos10-fsivr/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/home2/arcos/arcos-app/arcos10-fsivr/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home2/arcos/arcos-app/arcos10-fsivr/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home2/arcos/arcos-app/arcos10-fsivr/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 8,
  metadata:
   Metadata {
     _internal_repr:
      { 'google.rpc.help-bin': [Array],
        'grpc-status-details-bin': [Array] } },
  details:
   'Quota exceeded for quota metric \'speech.googleapis.com/default_requests\' and limit \'DefaultRequestsPerMinutePerProject\' of service \'speech.googleapis.com\' for consumer \'project_number:##########\'.' }

```

The same error is received by the `errHandler` registered on the `stream` and also by `process.on("uncaughtException")`

**Comment by kidplug** [comment]
Seems similar in a way to another issue in which any invalid or missing credentials would throw an "unhandledRejection" event to `process` - rather than giving the caller of the library the chance to handle it.

**Comment by kidplug** [comment]
I'm trying to look through the code that leads to the uncaughtException and found this in the nodejs docs:

> Error events#
When an error occurs within an EventEmitter instance, the typical action is for an 'error' event to be emitted. These are treated as special cases within Node.js.
>  If an EventEmitter does not have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.

Seems that the actual "stream" object from `streamingRecognize` is an instance of `Pumpify` which inherits from `Duplixify` which inherits from node native `stream.Duplex` .

Maybe the 'error' event from the underlying stream isn't being listened for properly...?

**Comment by kidplug** [comment]
hm - I wonder if in my code, I had either (a) not yet listened for "error" or (b) had already unlistened for "error" but another "error" occurred and there was no longer any listener for it...

**Comment by laljikanjareeya** [comment]
Thanks for reporting the issue, I tried using latest version of `@google-cloud/speech` with below code(taken from sample) and it's working as expected.
can you provide the version which you are using and complete code sample than We can dig into more.
also tried below code in loop but it's not crashing the entire node process.
```javascript
async function main() {

    const fs = require('fs');
    const filename = 'H:/audio.raw';
    const speech = require('@google-cloud/speech');

    const client = new speech.SpeechClient();
    const request = {
        config: {
            encoding: 'LINEAR16',
            sampleRateHertz: 16000,
            languageCode: 'en-US',
        },
        interimResults: false,
    };

    const recognizeStream = client
        .streamingRecognize(request)
        .on('error', (err) => {
            console.error(err) //got error here
        })
        .on('data', data => {
            console.log(
                `Transcription : ${data.results[0].alternatives[0].transcript}`
            );
        });
    fs.createReadStream(filename).pipe(recognizeStream);
}

process
    .on('unhandledRejection', (reason, p) => {
        console.error(reason, 'Unhandled Rejection at Promise', p);
    })
    .on('uncaughtException', err => {
        console.error(err, 'Uncaught Exception thrown');
    });

main().catch(console.error);
```

it throws exception as below while Quota exceed:
```
{ Error: Quota exceeded for quota metric 'speech.googleapis.com/default_requests' and limit 'DefaultRequestsPerMinutePerProject' of service 'speech.googleapis.com' for consumer 'project_number:##########'.
    at Http2CallStream.call.on (f:\common-test\speech-demos\node_modules\@grpc\grpc-js\build\src\call.js:68:41)
    at Http2CallStream.emit (events.js:203:15)
    at process.nextTick (f:\common-test\speech-demos\node_modules\@grpc\grpc-js\build\src\call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 8,
  details:
   'Quota exceeded for quota metric \'speech.googleapis.com/default_requests\' and limit \'DefaultRequestsPerMinutePerProject\' of service \'speech.googleapis.com\' for consumer \'project_number:##########\'.',
  metadata:
   Metadata {
     options: undefined,
     internalRepr:
      Map {
        'google.rpc.help-bin' => [Array],
        'grpc-status-details-bin' => [Array] } } }
```
